-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 00:52:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema musicplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musicplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musicplus` DEFAULT CHARACTER SET utf8 ;
USE `musicplus` ;

-- -----------------------------------------------------
-- Table `musicplus`.`epoca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`epoca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`compositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`compositor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(155) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `bio` TEXT NOT NULL,
  `epoca_id` INT NOT NULL,
  `pais_nascimento_id` INT NOT NULL,
  `data_falescimento` DATE NULL,
  `pais_falescimento_id` INT NULL,
  `imagem_principal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compositor_epoca1_idx` (`epoca_id` ASC),
  INDEX `fk_compositor_pais1_idx` (`pais_nascimento_id` ASC),
  INDEX `fk_compositor_pais2_idx` (`pais_falescimento_id` ASC),
  CONSTRAINT `fk_compositor_epoca1`
    FOREIGN KEY (`epoca_id`)
    REFERENCES `musicplus`.`epoca` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compositor_pais1`
    FOREIGN KEY (`pais_nascimento_id`)
    REFERENCES `musicplus`.`pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compositor_pais2`
    FOREIGN KEY (`pais_falescimento_id`)
    REFERENCES `musicplus`.`pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(155) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NULL,
  `perfil_id` INT NOT NULL,
  `genero` TINYINT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil_idx` (`perfil_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `musicplus`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`tonalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`tonalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `cor` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`composicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`composicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo_completo` VARCHAR(155) NOT NULL,
  `texto_informativo` TEXT NOT NULL,
  `data_composicao` DATE NOT NULL,
  `pais_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `tonalidade_id` INT NOT NULL,
  `partitura_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_composicao_pais1_idx` (`pais_id` ASC),
  INDEX `fk_composicao_genero1_idx` (`genero_id` ASC),
  INDEX `fk_composicao_tonalidade1_idx` (`tonalidade_id` ASC),
  CONSTRAINT `fk_composicao_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `musicplus`.`pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_composicao_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `musicplus`.`genero` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_composicao_tonalidade1`
    FOREIGN KEY (`tonalidade_id`)
    REFERENCES `musicplus`.`tonalidade` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`imagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(155) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`bebida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `teor_alcoolico` FLOAT NOT NULL,
  `amadurecimento` VARCHAR(155) NULL,
  `descricao` TEXT NOT NULL,
  `safra` VARCHAR(155) NULL,
  `tipo` VARCHAR(155) NULL,
  `uva` VARCHAR(155) NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bebida_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_bebida_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `musicplus`.`pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`marco_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`marco_historico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marco_historico_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_marco_historico_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `musicplus`.`pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`arte_afim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`arte_afim` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  `autor` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`epoca_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`epoca_imagem` (
  `epoca_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`epoca_id`, `imagem_id`),
  INDEX `fk_epoca_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_epoca_imagem_epoca1_idx` (`epoca_id` ASC),
  CONSTRAINT `fk_epoca_imagem_epoca1`
    FOREIGN KEY (`epoca_id`)
    REFERENCES `musicplus`.`epoca` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_epoca_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`bebida_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`bebida_imagem` (
  `bebida_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`bebida_id`, `imagem_id`),
  INDEX `fk_bebida_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_bebida_imagem_bebida1_idx` (`bebida_id` ASC),
  CONSTRAINT `fk_bebida_imagem_bebida1`
    FOREIGN KEY (`bebida_id`)
    REFERENCES `musicplus`.`bebida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bebida_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`marco_historico_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`marco_historico_imagem` (
  `marco_historico_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`marco_historico_id`, `imagem_id`),
  INDEX `fk_marco_historico_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_marco_historico_imagem_marco_historico1_idx` (`marco_historico_id` ASC),
  CONSTRAINT `fk_marco_historico_imagem_marco_historico1`
    FOREIGN KEY (`marco_historico_id`)
    REFERENCES `musicplus`.`marco_historico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_marco_historico_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`arte_afim_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`arte_afim_imagem` (
  `arte_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`arte_id`, `imagem_id`),
  INDEX `fk_arte_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_arte_imagem_arte1_idx` (`arte_id` ASC),
  CONSTRAINT `fk_arte_imagem_arte1`
    FOREIGN KEY (`arte_id`)
    REFERENCES `musicplus`.`arte_afim` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_arte_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`composicao_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`composicao_imagem` (
  `obra_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`obra_id`, `imagem_id`),
  INDEX `fk_obra_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_obra_imagem_obra1_idx` (`obra_id` ASC),
  CONSTRAINT `fk_obra_imagem_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `musicplus`.`composicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_obra_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`compositor_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`compositor_imagem` (
  `compositor_id` INT NOT NULL,
  `imagem_id` INT NOT NULL,
  PRIMARY KEY (`compositor_id`, `imagem_id`),
  INDEX `fk_compositor_imagem_imagem1_idx` (`imagem_id` ASC),
  INDEX `fk_compositor_imagem_compositor1_idx` (`compositor_id` ASC),
  CONSTRAINT `fk_compositor_imagem_compositor1`
    FOREIGN KEY (`compositor_id`)
    REFERENCES `musicplus`.`compositor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compositor_imagem_imagem1`
    FOREIGN KEY (`imagem_id`)
    REFERENCES `musicplus`.`imagem` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`composicao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`composicao_usuario` (
  `composicao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`composicao_id`, `usuario_id`),
  INDEX `fk_composicao_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_composicao_usuario_composicao1_idx` (`composicao_id` ASC),
  CONSTRAINT `fk_composicao_usuario_composicao1`
    FOREIGN KEY (`composicao_id`)
    REFERENCES `musicplus`.`composicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_composicao_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `musicplus`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`compositor_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`compositor_usuario` (
  `compositor_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`compositor_id`, `usuario_id`),
  INDEX `fk_compositor_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_compositor_usuario_compositor1_idx` (`compositor_id` ASC),
  CONSTRAINT `fk_compositor_usuario_compositor1`
    FOREIGN KEY (`compositor_id`)
    REFERENCES `musicplus`.`compositor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compositor_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `musicplus`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`epoca_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`epoca_usuario` (
  `epoca_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`epoca_id`, `usuario_id`),
  INDEX `fk_epoca_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_epoca_usuario_epoca1_idx` (`epoca_id` ASC),
  CONSTRAINT `fk_epoca_usuario_epoca1`
    FOREIGN KEY (`epoca_id`)
    REFERENCES `musicplus`.`epoca` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_epoca_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `musicplus`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musicplus`.`composicao_compositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicplus`.`composicao_compositor` (
  `composicao_id` INT NOT NULL,
  `compositor_id` INT NOT NULL,
  PRIMARY KEY (`composicao_id`, `compositor_id`),
  INDEX `fk_composicao_compositor_compositor1_idx` (`compositor_id` ASC),
  INDEX `fk_composicao_compositor_composicao1_idx` (`composicao_id` ASC),
  CONSTRAINT `fk_composicao_compositor_composicao1`
    FOREIGN KEY (`composicao_id`)
    REFERENCES `musicplus`.`composicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_composicao_compositor_compositor1`
    FOREIGN KEY (`compositor_id`)
    REFERENCES `musicplus`.`compositor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
